#ifndef BCOVIEWCORE_GLOBAL_H
#define BCOVIEWCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BCOVIEWCORE_LIBRARY)
#  define BCOVIEWCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define BCOVIEWCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BCOVIEWCORE_GLOBAL_H
